server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fabio-RM/sample-ecommerce-config-repo.git
          default-label: main
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9000/realms/sample-ecommerce